version: '3.8'

services:
  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=noprep-manager
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d econome"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
