# Generated by Django 5.1.1 on 2024-09-20 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('born_date', models.DateField(help_text='Data de nascimento do piloto')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(help_text='Cidade de origem do piloto', max_length=30)),
                ('state', models.CharField(help_text='Estado de origem do piloto', max_length=19)),
                ('hashed_tax_id', models.CharField(help_text='Documento de indentificação (CPF)', max_length=64, unique=True)),
                ('masked_tax_id', models.CharField(blank=True, help_text='Documento de indentificação (CPF) com máscara', max_length=14, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
