# Generated by Django 5.1 on 2024-08-22 02:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('born_date', models.DateField(help_text='Data de nascimento do piloto')),
                ('city', models.CharField(help_text='Cidade de origem do piloto', max_length=30)),
                ('state', models.CharField(help_text='Estado de origem do piloto', max_length=19)),
                ('tax_id', models.CharField(help_text='Documento de indentificação (CPF)', max_length=11, unique=True)),
                ('license_number', models.CharField(blank=True, help_text='Número da carteira de habilitação', max_length=9, null=True, unique=True)),
                ('category', models.CharField(choices=[('--', '--'), ('PAR-A - Piloto de Arrancada', 'PAR-A - Piloto de Arrancada'), ('PAR-B - Piloto de Arrancada', 'PAR-B - Piloto de Arrancada'), ('PARDJ - Piloto de Arrancada Drag Junior', 'PARDJ - Piloto de Arrancada Drag Junior'), ('PPNE-AR - Piloto Portador de Necessidades Especiais - Arrancada', 'PPNE-AR - Piloto Portador de Necessidades Especiais - Arrancada'), ('LPU-AR - Licença Prova Única - Arrancada', 'LPU-AR - Licença Prova Única - Arrancada')], help_text='Categoria da licença', max_length=63)),
                ('cba_number', models.CharField(blank=True, help_text='Número de registro CBA', max_length=12, null=True, unique=True)),
                ('federation', models.CharField(choices=[('--', '--'), ('FSA', 'FSA'), ('FAAES', 'FAAES'), ('FAB', 'FAB'), ('FAEP', 'FAEP'), ('FASP', 'FASP'), ('FAERJ', 'FAERJ'), ('FAUESC', 'FAUESC'), ('FCA', 'FCA'), ('FAMS', 'FAMS'), ('FGA', 'FGA'), ('FMA', 'FMA'), ('FEPAUTO', 'FEPAUTO'), ('FPEA', 'FPEA'), ('FPARN', 'FPARN'), ('FPRA', 'FPRA'), ('FAUGO', 'FAUGO'), ('FADF', 'FADF'), ('FAEM', 'FAEM'), ('FAA', 'FAA'), ('FAT', 'FAT'), ('FAEMT', 'FAEMT'), ('FAEPI', 'FAEPI'), ('MMC', 'MMC')], help_text='Federação de origem do piloto', max_length=7)),
                ('user', models.OneToOneField(help_text='Usuário associado ao piloto', on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Piloto',
                'verbose_name_plural': 'Pilotos',
            },
        ),
    ]
