# Generated by Django 5.1.1 on 2024-09-20 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racehistory',
            name='event',
            field=models.ForeignKey(help_text='Evento relacionado ao histórico', on_delete=django.db.models.deletion.CASCADE, related_name='race_history', to='events.event'),
        ),
        migrations.AddField(
            model_name='laptime',
            name='race_history',
            field=models.ForeignKey(help_text='Histórico de corrida ao qual essa volta pertence', on_delete=django.db.models.deletion.CASCADE, related_name='laps_time', to='drivers.racehistory'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(help_text='Piloto relacionado ao Veículo', on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('license_number__isnull', True), _negated=True), fields=('license_number',), name='unique_license_number'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('cba_number__isnull', True), _negated=True), fields=('cba_number',), name='unique_cba_number'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('plate_number__isnull', True), _negated=True), fields=('plate_number',), name='unique_plate_number'),
        ),
    ]
