# Generated by Django 5.1 on 2024-08-29 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='cba_number',
            field=models.CharField(blank=True, help_text='Número de registro CBA', max_length=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('cba_number__isnull', True), _negated=True), fields=('cba_number',), name='unique_cba_number'),
        ),
    ]
