# Generated by Django 5.1 on 2024-08-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='ends_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='star_time',
        ),
        migrations.AddField(
            model_name='event',
            name='starts_at',
            field=models.TimeField(blank=True, help_text='Horário de Início do Evento', null=True),
        ),
    ]
